name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-deph: 0

                  
    - name: Git Semantic Version              
      uses: PaulHatch/semantic-version@v5.0.1
      with:
        major_pattern: "major:"
        minor_pattern: "feat:"
        format: "${major}.${minor}.${patch}-prerelease${increment}"
      id: version
      # el id hace referencia al producto del paso de arriba
        
    - name: Docker Login
      env: 
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        NEW_VERSION: ${{ steps.version.outputs.version }}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
        echo "New version: $NEW_VERSION!!!!!!!!"

    # - name: Build Docker Image 
    #   run: |
    #       docker build -t silvester022/graphql:0.0.2 .
    #       docker build -t silvester022/graphql:latest .
    
    # - name: Push Docker Image 
    #   run: |
    #       docker push silvester022/graphql:0.0.2
    #       docker push silvester022/graphql:latest

    






    
    # - name: Build the Docker image
    #   run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
